### ISSUE TITLE
.mdt files management problems

### ISSUE THREAD

**Issue by Zerk** [wisk/medusa#1]
- If the file /bin_dir_path/bin_name.mdt doesn't exist and is in a writable directory, no choice is given for the .mdt file location and name
- If the file /bin_dir_path/bin_name.mdt already exists the "replace" option doesn't work
- "cancel" button doesn't cancel the opening process, it only closes and re-open the same window

**Comment by wisk** [comment]
Both the second and third should be fixed by commits 2d5fda9b15937c3a0ef7acab436d028df540f8b6 and 7d7297793c89dcfc4fde0380f51fef17e55741e9, however I'm afraid the first one requires to redesign the module dialogbox so it'll take a while before get fixed.

**Comment by wisk** [comment]
Regarding the first issue, I think it's better to automatically save the file on the same folder with the name _<filename>.<db_ext>_. It's the behavior of IDA which everybody is used to.
