### ISSUE TITLE
typo in code

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#11]
https://github.com/wisk/medusa/blob/dev/src/core/module.cpp#L172

TGetDabatase pGetDatabase 

https://github.com/wisk/medusa/blob/dev/inc/medusa/database.hpp#L123

typedef Database\* (*TGetDabatase)(void);

**Comment by wisk** [comment]
Sorry, I didn't get it. Where's the typo?

**Comment by Necrolis** [comment]
I think he means the misspelling of "database", ie: `typedef Database* (*TGetDabatase)(void);` should be `typedef Database* (*TGetDatabase)(void);`

**Comment by wisk** [comment]
Oh right! Nice catch, thanks :)

**Comment by wisk** [comment]
The patch https://github.com/wisk/medusa/commit/46ad32fc1da270f49493c7c5e8154e1594fee5e5 solves this issue, thanks again.
