### ISSUE TITLE
About the name...

### ISSUE THREAD

**Issue by freezeeedos** [wisk/medusa#13]
"Medusa" is the name of another well known open source project: https://launchpad.net/ubuntu/+source/medusa
I thought you guys should know...

Awesome project, by the way

**Comment by wisk** [comment]
Yep, we were aware about that. But back in the 2011's, it was too late to change it since this project was validated by our school. :)
I don't think it'd be a good idea to change the name now, I don't want to confuse people.

Thank you for the support.
