### ISSUE TITLE
Cannot open file from command line with qMedusa

### ISSUE THREAD

**Issue by pfalcon** [wisk/medusa#17]
When I run "qMedusa <executable>", qMedusa just starts with empty windows, ignoring argument. It would be nice if it instead opened the given executable as if with Open->File menu.

Besides pure command-line convenience, this would reduce much the confusion for weird cases like #14.

**Comment by wisk** [comment]
Sorry for the delay. If I understand correctly, you want qMedusa to be able to take an executable path as argument to open it automatically?

**Comment by pfalcon** [comment]
Hello,

On Sat, 25 Oct 2014 14:03:00 -0700
wisk notifications@github.com wrote:

> Sorry for the delay. If I understand correctly, you want qMedusa to
> be able to take an executable path as argument to open it
> automatically?

Yes, correct.

## 

Best regards,
 Paul                          mailto:pmiscml@gmail.com

**Comment by wisk** [comment]
I quickly implemented it on the branch operand-as-expressions (https://github.com/wisk/medusa/commit/6f53dffd1e072c187cc0dd0c3c9fb6159d62f4d7).
Please, tell me if it's ok for you. :)

**Comment by pfalcon** [comment]
Works well, thanks!
