### ISSUE TITLE
Mac OS X Unix Module

### ISSUE THREAD

**Issue by saeschdivara** [wisk/medusa#18]
Hey,

I wanted to say that your code for unique_module.cpp needs an update so that it works too on OS X:

``` c++
char const* Module::GetExtension(void)
{
#ifdef __APPLE__
    return "dylib";
#else
    return "so";
#endif
}
```

**Comment by wisk** [comment]
I will apply this patch ASAP, thanks for sharing! :)

**Comment by saeschdivara** [comment]
Thank you for this awesome application :)

**Comment by wisk** [comment]
It's fixed https://github.com/wisk/medusa/commit/3f1a16c6c91b2e43debc50be1732092029a66140 thanks again and glad you like this project. :)
