### ISSUE TITLE
I can not compile the project

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#2]
Kubundu 14.04 Boost 1.55

/home/ivan/projects/medisa_project/medusa/src/ui/qt/SettingsDialog.cpp:8:28: fatal error: QKeySequenceEdit:
 #include <QKeySequenceEdit>
                            ^
compilation terminated.

cmake .. -DOGDF_PATH:PATH=/home/ivan/projects/medisa_project/ogdf/ -DQT5_CMAKE_PATH:PATH=/home/ivan/programmertools/qt/5.2.0/gcc/lib/cmake

I have tried different versions of qt:

cmake .. -DOGDF_PATH:PATH=/home/ivan/projects/medisa_project/ogdf/ -DQT5_CMAKE_PATH:PATH=/home/ivan/programmertools/qt/5.3/gcc/lib/cmake

cmake .. -DOGDF_PATH:PATH=/home/ivan/projects/medisa_project/ogdf/ -DQT5_CMAKE_PATH:PATH=/home/ivan/programmertools/qt/5.0.2/gcc/lib/cmake

**Comment by wisk** [comment]
It seems QKeySequenceEdit is only available since Qt 5.2 (http://qt-project.org/doc/qt-5/qkeysequenceedit.html).
Could you update your version of Qt and try again?

**Comment by ivan-kulikov-dev** [comment]
Ok.Compiled successfully.thanks!
