### ISSUE TITLE
OGDF OS X Build Failure

### ISSUE THREAD

**Issue by saeschdivara** [wisk/medusa#20]
Reference: https://github.com/ogdf/ogdf/issues/11

```
if("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
  #if(${CMAKE_SYSTEM_VERSION} MATCHES "todo-some-number-here")
       add_definitions("-DGTEST_USE_OWN_TR1_TUPLE=1")
  #endif()
endif()
```

This should be added to the main CMakeLists.txt

**Comment by wisk** [comment]
I'll try to fix it, thanks for reporting.

**Comment by saeschdivara** [comment]
Well for me it woks on OS X and since it checks if the system is Darwin,
there should be no problem for you
