### ISSUE TITLE
Can you add http://www.appveyor.com/ Cl-build for medusa

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#22]
Can you add http://www.appveyor.com/ Cl-build for medusa?(windows build) .(Service is free for open source projects) I can help to setting this :)

**Comment by wisk** [comment]
Thank for the info, that's exactly what I was looking for.
However, I've some concerns regarding the dependencies, do you know how to handle boost and qt5.4?

**Comment by ivan-kulikov-dev** [comment]
precompiled binaries :) (boost and qt)

**Comment by wisk** [comment]
It seems they are included in the **unstable** image :)
