### ISSUE TITLE
medusa crashed while open bitlocker-mbr.bs.x86-16

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#27]
medusa crashed while open bitlocker-mbr.bs.x86-16
(qMedusa)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pydusa
commit 7019aa100b0f2e2ad31b6d18f503e6af130e3d59 (current)

**Comment by wisk** [comment]
I had the same issue with test_bind, I don't know why Python on Linux doesn't want to load module from the current working directory (which is the case on Windows). Adding the path where pydusa.so is located into the environment variable `PYTHONPATH` fixes this issue.
I'll try to implement a clean way to do so.
Thanks for reporting! :)

**Comment by kaniini** [comment]
Just have your bootstrap script do `sys.path.append(...)` it is cleaner.

**Comment by wisk** [comment]
Should be fixed with https://github.com/wisk/medusa/commit/4f70ddbc2299ebfa2e8c8e53854f4ee4aa47d15c
Thanks again
