### ISSUE TITLE
my script for install cmake to travis (cmake 3.2.1)

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#31]
my script for install cmake to travis (cmake 3.2.1)
very quick ;)

https://raw.githubusercontent.com/gunmetalbackupgooglecode/pdbparser/master/.travis.yml

https://raw.githubusercontent.com/gunmetalbackupgooglecode/pdbparser/master/installcmake.sh

**Comment by wisk** [comment]
That's look really great, thanks for sharing :)

**Comment by ivan-kulikov-dev** [comment]
-  wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sudo ./installcmake.sh
  - ls /usr/cmake-3.2.1-Linux-x86_64
  - sudo ln -s /usr/cmake-3.2.1-Linux-x86_64/bin/cmake /usr/bin/cmake

https://raw.githubusercontent.com/gunmetalbackupgooglecode/pdbparser/master/installcmake.sh

**Comment by wisk** [comment]
I added your PR, thanks for your work. :)
However, it seems there's still an issue with g++

```
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [src/bind/python/CMakeFiles/pydusa.dir/py_architecture.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/bind/python/CMakeFiles/pydusa.dir/all] Error 2
make: *** [all] Error 2
```

I'll try to update the version of g++, and hope for the best. :)

**Comment by ivan-kulikov-dev** [comment]
How many memory on travis?(may not have enough RAM for parallel build ?)

**Comment by wisk** [comment]
I don't know, but I had to reduce the number of parallel build from 3 to 2.

**Comment by moul** [comment]
https://travis-ci.com/plans
- 3GB of memory
- up to 2 cores

**Comment by ivan-kulikov-dev** [comment]
- wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
- chmod +x cmake-3.2.1-Linux-x86_64.sh
- mkdir $HOME/cmake
- sh cmake-3.2.1-Linux-x86_64.sh --skip-license --prefix=$HOME/cmake

# 
- $HOME/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release
