### ISSUE TITLE
I want add support windows pdb files

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#4]
Hi.I have question about architecture.I want add support windows pdb files.
My algoritm is:
1)parse PE_DIRECTORY_ENTRY_DEBUG
2)try download  pdb file from microsoft site
3)valid pdb file
4)if file not system,then try load user pdb file.(filename.pdb)
5)parse pdb file and add comments

questions:
1)Pe loader parse PE_DIRECTORY_ENTRY_DEBUG.Can be add IsHasDebugSymbols to Loader?Download symbols with TaskManager?(AddTask)

**Comment by wisk** [comment]
Hello,

That's a really good idea!
I don't think a new method for the class _Loader_ is needed, the method _Loader::Map_ should be enough to parse the PDB and fills the _Document_.
However, as you noted, the user can define **_NT_SYMBOL_PATH** to specify a remote server which could provide the PDB. This behavior requires a specific task and API to download file.

Tell me what you need, I'll try to implement it.

BTW, are you going to implement it from scratch or relying on an external library?

**Comment by ivan-kulikov-dev** [comment]
No, i'll rewrite this https://code.google.com/p/pdbparser/ .

**Comment by ivan-kulikov-dev** [comment]
https://github.com/gunmetal313/medusa/tree/addpdb my branch

**Comment by wisk** [comment]
Hi gunmetal313,

Because I didn't have news regarding this feature for a long time, I close this issue.
Feel free to re-open it if you have made some progresses.

Thanks.
