### ISSUE TITLE
Boost 1.59 incompatibility

### ISSUE THREAD

**Issue by durandj** [wisk/medusa#42]
The documentation currently says that any version of Boost greater than or equal to 1.55 should work but when trying to compile against 1.59 you get compile errors about missing `BOOST_MESSAGE`. Switching to 1.55 fixes this. May need to update the documentation to mention that 1.59 is not compatible.

**Comment by wisk** [comment]
Hi durandj,

Sorry for the late and thank you for reporting this issue, I wasn't aware that `BOOST_MESSAGE` was deprecated. Replacing `BOOST_MESSAGE` to `BOOST_TEXT_MESSAGE` (https://github.com/wisk/medusa/commit/84e927a61eb6a3017c2aeede6b5826c7ce03460f) should fix this problem.

Please, tell me if it's ok now. :)

**Comment by durandj** [comment]
Seems all good! Thanks :)
