### ISSUE TITLE
test_arch uses a non existent BOOST_MESSAGE 

### ISSUE THREAD

**Issue by neitsa** [wisk/medusa#52]
Hi :)

**OS**: Windows 10 x64
**Boost version**: 1.60.0
**Tool Chain**:  Visual Studio C++ 2013 Update 5
**Current commit**:
$ git rev-parse --verify HEAD
0237f8082731a824286b9f98625d1ef79deec20f

In test_arch.cpp it seems that the test for st62 architecture is using an older boost message style (`BOOST_MESSAGE` instead of `BOOST_TEST_MESSAGE`) which ultimately results in a compile error (at least if using Boost 1.60.0).

see: https://github.com/wisk/medusa/blob/dev/src/test/test_arch.cpp#L339

Let me know if I'm right or I have missed something.

P.S : compile target is ALL_BUILD, and I'm compiling without Qt

Thank you ! <3

**Comment by wisk** [comment]
Hi neitsa :)

Thanks for reporting, it was fixed here https://github.com/wisk/medusa/commit/4dcd2959282a883aa5ba56ae1566140a36f9773d
