### ISSUE TITLE
x86 Release?

### ISSUE THREAD

**Issue by halsten** [wisk/medusa#54]
Any chance you can release an x86 release version of the project? It looks really impressive and very promising, would be nice to be able to play with it before diving into the source repository and compiling everything.

**Comment by wisk** [comment]
Hi halsten, and thanks for your interest on this project.
By "x86 release" you mean a 32-bit or 64-bit version of medusa?
(64-bit version would be easier for me to build. :))

**Comment by halsten** [comment]
Hi wis! Thank you for the fast reply. My apologies on the confusion, but I was wondering if there will be a 32-bit release of medusa. Also I had some questions that were probably not the place for them in here, since they are not issues but related to medusa's development. Would you be interested in exchanging emails? Anyways, this really looks very promising as a standard tool if it can get more work. I am in the same boat really, similar project turned to dead after a while unfortunately.

**Comment by wisk** [comment]
No worry. :)
Medusa could be compiled on both 32-bit and 64-bit. Unfortunately, at this time, we still don't own a specific machine to provide pre-built versions of Medusa, I hope we'll able to offer this kind of service soon.
Now, regarding 32-bit version of Windows, I see 2 potentials issues here: 32-bit version of Windows tends to disappear (at least on x86) and it's important to know if users want a wxp compatible version (Microsoft starts to break compatibility with Windows XP).
Anyways, if you want me to build you a 32-bit version for Windows, just tell me your Windows version and I'll give a try asap, but I think it'd be faster to build it yourself.

Sure, I'm not fan to leave a my email address here, give me your address here or on IRC and I'll ping you back (, probably tomorrow).

**Comment by halsten** [comment]
Thanks a lot for the lengthy reply and the support. I will get in contact with you via IRC then. Thanks. :)
