### ISSUE TITLE
 add functionality  

### ISSUE THREAD

**Issue by ivan-kulikov-dev** [wisk/medusa#7]
Please add 
https://github.com/wisk/medusa/blob/master/inc/medusa/configuration.hpp#L88
InsertStringField()
GetStringField()
InsertNumberField(only numbers in field,useful when selecting the parameters of the uploaded file)
GetNumberField()
InsertFilePathField()

**Comment by wisk** [comment]
Hi @gunmetal313, this commit https://github.com/wisk/medusa/commit/20efb922dc71e10e0a0781bd5f6990240ab5d343 adds the support for both string and path. Regarding the number, I need to know if you need a specific size? (e.g.: u8, u16, u32, u64) I think storing the value in a u64 value type should be enough and easier to implement.
BTW, I didn't test the code; so please tell me if you encounter any issues.

**Comment by ivan-kulikov-dev** [comment]
PeLoader::PeLoader(void) : m_Machine(PE_FILE_MACHINE_UNKNOWN), m_Magic(0x0)
{
    m_CfgMdl.InsertString("getmytext");
}

void PeLoader::Map(Document& rDoc, Architecture::VectorSharedPtr const& rArchs) {
  Log::Write("ldr_pe") << m_CfgMdl.GetString("getmytext") << LogEnd;
///////////

![noooo](https://cloud.githubusercontent.com/assets/4685934/4084628/a2ea52ae-2f0c-11e4-849b-02cf045377e5.png)

**Comment by wisk** [comment]
Please try https://github.com/wisk/medusa/commit/f14057c366d94fd55ddd86f3470b1fb8d9fcea80 and tell me if it's better or not. :)

**Comment by ivan-kulikov-dev** [comment]
InsertString - ok
InsertUint64 - ok
