### ISSUE TITLE
Build broken due to changes in PEGTL

### ISSUE THREAD

**Issue by dnivra** [wisk/medusa#71]
`pegtl::action_input` has been removed from current master and thus, medusa fails to build when running `make`. I changed the tag for PEGTL(in CMakeLists.txt) to point to commit [ba225fd3dd](https://github.com/ColinH/PEGTL/commit/ba225fd3dd) and the build succeeded. `pegtl::action_input` was removed in [the next commit](https://github.com/ColinH/PEGTL/commit/d2d30246).

**Comment by wisk** [comment]
Hi dnivra,

Thanks for reporting, I'll take a look. :)

**Comment by wisk** [comment]
Sorry for the late, you were right and now it's fixed.
Thanks for reporting. :)
https://github.com/wisk/medusa/commit/11eace2699928b64126ade9ad0c148ab457fa51e
