### ISSUE TITLE
Show seems to be removed from database after switching to anime

### ISSUE THREAD

**Issue by nterupt** [wisk/medusa#81]
After switching a show to anime, if I then attempt to redit details of the show I get the following pop-up error in my brower, "Could not get series info for: tvdb171591" in this case.  Also, if I attempt to manually post-process episodes of this show the script reports an error saying: "This show isn't in your list, you need to add it before post-processing an episode"

Looking at the logs I cannot see any error being generated when I switch the show to anime.

![error](https://user-images.githubusercontent.com/3375654/45933914-abcbf600-bf5b-11e8-9ca0-21cf71bf78ae.png)

**Comment by kaniini** [comment]
this is the big tracker for Medusa disassembler not whatever that web application is

**Comment by nterupt** [comment]
Apologies, must have misclicked when searching through gitHub.
